@host=https://localhost:7101
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJUYWptYSIsImZhbWlseV9uYW1lIjoiSGVpbnoiLCJqdGkiOiI5NmU1Y2U5MS0wY2NiLTQwNmUtYmIyMy05MTA2YjZhOTI2OWMiLCJleHAiOjE2NzMzNjQ4NzUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.Rgi_iJKY5FV-DRgqQCxKxXm3VI7GXs7HTW68zW1rCbA

## organizations By Id
GET {{host}}/api/organizations/108
Content-Type: application/json
Authorization: Bearer {{token}}
###

## organizations by pageindex and pagesize
POST {{host}}/api/organizations/paged
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "searchfilter": "017",
  "pageIndex": 1,
  "pageSize": 10
}
###
## organizations Id, NAme list
GET {{host}}/api/organizations/lookup
Content-Type: application/json
#Authorization: Bearer {{token}}

###
## Check duplicate organizations name exists duplicate/{nametoCheck}
GET {{host}}/api/organizations/duplicate/Maruti - UP2
Content-Type: application/json
Authorization: Bearer {{token}}

###
## Create organizations

POST https://localhost:7101/api/organizations
Content-Type: application/json
x-idempotency-key:{BC42D7AF-8511-4F71-901B-2422C63EEDC1}
Authorization: Bearer {{token}}

{
  "name": "018-FIRST ORG",
  "organizationsCode": "BR-001",
  "organizationsId": 108,
  "businessType": 1,
  "isActive": true,
  "isDeleted": false
}

###
## Update organizations
PUT https://localhost:7101/api/organizations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id":104,
  "name": "Test-organizations-001-UPD",
  "organizationsCode": "BR-001-UPD",
  "businessType": 1,
  "isActive": true,
  "isDeleted": false
}

###
## Delete organizations
DELETE https://localhost:7101/api/organizations/43
Content-Type: application/json
Authorization: Bearer {{token}}
