// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToolWindow
{
    internal sealed partial class Vsix
    {
        public const string Id = "ToolWindow.9060ee28-7d6d-4346-9f8b-e57237f47cb8";
        public const string Name = "ToolWindow";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
